service: game-store-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    MONGO_URI: ${ssm:/game-store/MONGO_URI}
    JWT_SECRET: ${ssm:/game-store/JWT_SECRET}
    RAZORPAY_KEY_ID: ${ssm:/game-store/RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${ssm:/game-store/RAZORPAY_KEY_SECRET}
    AWS_S3_BUCKET: ${ssm:/game-store/AWS_S3_BUCKET}
    FRONTEND_URL: ${ssm:/game-store/FRONTEND_URL}

functions:
  api:
    handler: app.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-offline
